// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCuXHIJnzVIA9lTfQm1F0xfXbbHqGNDdDE',
    appId: '1:413788721994:web:d8ac94b5773e57a644e7b3',
    messagingSenderId: '413788721994',
    projectId: 'burclar-bozki-fire',
    authDomain: 'burclar-bozki-fire.firebaseapp.com',
    storageBucket: 'burclar-bozki-fire.appspot.com',
    measurementId: 'G-L2RSV4P8XJ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDvVpUVE_dQem8bFuOyfXtnjRJ8bubkat0',
    appId: '1:413788721994:android:2f52577080f4b20c44e7b3',
    messagingSenderId: '413788721994',
    projectId: 'burclar-bozki-fire',
    storageBucket: 'burclar-bozki-fire.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC2KJ1jfKo0vGcNct4j6AeKweC9XQwXTn0',
    appId: '1:413788721994:ios:8a82742783871b1944e7b3',
    messagingSenderId: '413788721994',
    projectId: 'burclar-bozki-fire',
    storageBucket: 'burclar-bozki-fire.appspot.com',
    iosClientId: '413788721994-9q1ki1ti3vfvb3d0ej2o2o53q7t1m7sq.apps.googleusercontent.com',
    iosBundleId: 'com.bozki.burclar',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyC2KJ1jfKo0vGcNct4j6AeKweC9XQwXTn0',
    appId: '1:413788721994:ios:8a82742783871b1944e7b3',
    messagingSenderId: '413788721994',
    projectId: 'burclar-bozki-fire',
    storageBucket: 'burclar-bozki-fire.appspot.com',
    iosClientId: '413788721994-9q1ki1ti3vfvb3d0ej2o2o53q7t1m7sq.apps.googleusercontent.com',
    iosBundleId: 'com.bozki.burclar',
  );
}
